### ISSUE TITLE
Readme: Tooling

### ISSUE THREAD

**Issue by akaeba** [abdelazeem201/Design-and-ASICImplementation-of-32-Point-FFT-Processor#2]
Hi Ahmed,

realy nice project. Could you please add the tooling to your Readme.md. For Example something in that way:
1) RTL Simulation: Modelsim
2) Synthesis: Synopsis Design Compiler
3) P&R: Encounter
....

A real great deal would also to have an open source tooling. I think for the hobbyist costs this tooling a lot of licence fees.

BR,
Andreas

**Comment by abdelazeem201** [comment]
Hi Andreas,
Thank you for your Comment, and I have already edited the Readme.

regarding the tooling I have already simulated the FFT using different simulators "Synopsys VCS/Cadence's Incisive/ QuestaSim", also synthesis the Design using synopsys and Cadence tools and also OpenRoad

**Comment by akaeba** [comment]
Great :-) Thanks for sharing your tooling.

BR,
Andreas
